In [1]:
import numpy as np

In [2]:
prime_array = np.array([2,3,5,7,9])
print(prime_array)

[2 3 5 7 9]


In [3]:
print(prime_array.shape)

(5,)


In [4]:
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print(prim_array)

[[2 3 5 7 9]
 [1 2 3 4 5]]


In [5]:
print(prim_array.shape)

(2, 5)


In [6]:
#3d array
num_array = np.array([[[1,2,3],[2,3,4]],
                     [[3,4,5],[5,6,7]]])
print(num_array)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [5 6 7]]]


In [7]:
print(num_array.shape)

(2, 2, 3)


In [8]:
#4r array
num_arr =([[[[1,2],[2,3],[4,5],[8,6]],
           [2,3],[4,5],[5,6],[6,7]]])
print(num_arr)

[[[[1, 2], [2, 3], [4, 5], [8, 6]], [2, 3], [4, 5], [5, 6], [6, 7]]]


In [9]:
print(num_arr)

[[[[1, 2], [2, 3], [4, 5], [8, 6]], [2, 3], [4, 5], [5, 6], [6, 7]]]


#array Inspection
1#.ndarray.shape
#2.ndarray.ndim
#3.ndarray.size
#4.ndarray.dtype
#5.ndarray.astype

In [10]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print("Dimension of prim_array is =" ,prim_array.ndim)

Dimension of prim_array is = 2


In [11]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([2,3,5,7,9,7,7])
print("Dimension of prim_array is =" ,prim_array.ndim)

Dimension of prim_array is = 1


In [12]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9,7,7],[3,4,5,6,8,9,9]])
print("Dimension of prim_array is =" ,prim_array.ndim)

Dimension of prim_array is = 2


In [13]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print("Data type of prim_array is =" ,prim_array.dtype)

Data type of prim_array is = int32


In [14]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print("Data type of prim_array is =" ,prim_array.astype)

Data type of prim_array is = <built-in method astype of numpy.ndarray object at 0x000001C9110F97B0>


In [15]:
#different Type of n-d array
#Intializing  the array with Zeros
zeros_array = np.zeros((3,3)) #default data_type=float
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#Intializing  the array with Zeros
zeros_array = np.zeros((4,3),dtype=int) 
print(zeros_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
#print 0 to N
number_array =np.ones((4,2,3))
print(number_array)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [18]:
import numpy as np
num= np.empty([2,3])
print(num)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
#numerical Ranges
arr_range =np.arange(5)
print(arr_range)

[0 1 2 3 4]


In [20]:
# parameter for the function =np.arange(start ,stop,step)
arr_range =np.arange(2,21,2)
print(arr_range)

[ 2  4  6  8 10 12 14 16 18 20]


In [24]:
import numpy as np

arr_linspace =np.linspace(1,4,7 , endpoint=False,retstep=True)
print(arr_linspace)

(array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857]), 0.42857142857142855)


In [25]:
import numpy as np
arr = np.empty([2, 2])
print(arr)

[[2.12199579e-314 9.69752076e-312]
 [5.39519685e-321 3.62861281e-312]]
