In [1]:
import numpy as np

In [2]:
prime_array = np.array([2,3,5,7,9])
print(prime_array)

[2 3 5 7 9]


In [3]:
print(prime_array.shape)

(5,)


In [4]:
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print(prim_array)

[[2 3 5 7 9]
 [1 2 3 4 5]]


In [5]:
print(prim_array.shape)

(2, 5)


In [6]:
#3d array
num_array = np.array([[[1,2,3],[2,3,4]],
                     [[3,4,5],[5,6,7]]])
print(num_array)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [5 6 7]]]


In [7]:
print(num_array.shape)

(2, 2, 3)


In [8]:
#4r array
num_arr =([[[[1,2],[2,3],[4,5],[8,6]],
           [2,3],[4,5],[5,6],[6,7]]])
print(num_arr)

[[[[1, 2], [2, 3], [4, 5], [8, 6]], [2, 3], [4, 5], [5, 6], [6, 7]]]


In [9]:
print(num_arr)

[[[[1, 2], [2, 3], [4, 5], [8, 6]], [2, 3], [4, 5], [5, 6], [6, 7]]]


#array Inspection
1#.ndarray.shape
#2.ndarray.ndim
#3.ndarray.size
#4.ndarray.dtype
#5.ndarray.astype

In [10]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print("Dimension of prim_array is =" ,prim_array.ndim)

Dimension of prim_array is = 2


In [11]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([2,3,5,7,9,7,7])
print("Dimension of prim_array is =" ,prim_array.ndim)

Dimension of prim_array is = 1


In [12]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9,7,7],[3,4,5,6,8,9,9]])
print("Dimension of prim_array is =" ,prim_array.ndim)

Dimension of prim_array is = 2


In [13]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print("Data type of prim_array is =" ,prim_array.dtype)

Data type of prim_array is = int32


In [14]:
#ndim no of dimensiom
import numpy as np
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print("Data type of prim_array is =" ,prim_array.astype)

Data type of prim_array is = <built-in method astype of numpy.ndarray object at 0x000001C9110F97B0>


In [15]:
#different Type of n-d array
#Intializing  the array with Zeros
zeros_array = np.zeros((3,3)) #default data_type=float
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
#Intializing  the array with Zeros
zeros_array = np.zeros((4,3),dtype=int) 
print(zeros_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [17]:
#print 0 to N
number_array =np.ones((4,2,3))
print(number_array)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [18]:
import numpy as np
num= np.empty([2,3])
print(num)

[[0. 0. 0.]
 [0. 0. 0.]]


In [19]:
#numerical Ranges
arr_range =np.arange(5)
print(arr_range)

[0 1 2 3 4]


In [20]:
# parameter for the function =np.arange(start ,stop,step)
arr_range =np.arange(2,21,2)
print(arr_range)

[ 2  4  6  8 10 12 14 16 18 20]


In [24]:
import numpy as np

arr_linspace =np.linspace(1,4,7 , endpoint=False,retstep=True)
print(arr_linspace)

(array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857]), 0.42857142857142855)


In [25]:
import numpy as np
arr = np.empty([2, 2])
print(arr)

[[2.12199579e-314 9.69752076e-312]
 [5.39519685e-321 3.62861281e-312]]


In [26]:
#array  from numerical ranges
# array with values from 0 to N
array_with_range =np.arange(500)
array_with_range

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [27]:
array_with_range =np.arange(100,500,10)
array_with_range

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220,
       230, 240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350,
       360, 370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480,
       490])

In [29]:
#to get the number of evenly spaced vaues between intervals
#parameter for function -np.linespace (start,stop,num,endpoint,reststep)

linearly_spaced_values =np.linspace(1,2,50, endpoint = False,retstep=True)
linearly_spaced_values

(array([1.  , 1.02, 1.04, 1.06, 1.08, 1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 ,
        1.22, 1.24, 1.26, 1.28, 1.3 , 1.32, 1.34, 1.36, 1.38, 1.4 , 1.42,
        1.44, 1.46, 1.48, 1.5 , 1.52, 1.54, 1.56, 1.58, 1.6 , 1.62, 1.64,
        1.66, 1.68, 1.7 , 1.72, 1.74, 1.76, 1.78, 1.8 , 1.82, 1.84, 1.86,
        1.88, 1.9 , 1.92, 1.94, 1.96, 1.98]),
 0.02)

Array from the random number


In [30]:
random_array =np.random.random((6,2))
random_array

array([[0.72207114, 0.96447754],
       [0.12003943, 0.99762488],
       [0.09705311, 0.75047242],
       [0.71112222, 0.82397085],
       [0.84052786, 0.737651  ],
       [0.19747484, 0.82318737]])

In [31]:
# to get an array with random input integral element of desired shape
random_integral_array = np.random.randint(0,5,size=(2,3,4))
random_integral_array

array([[[0, 4, 4, 1],
        [1, 4, 2, 4],
        [0, 0, 4, 0]],

       [[4, 2, 1, 0],
        [1, 0, 4, 1],
        [1, 2, 4, 0]]])

In [32]:
a= np.full((5,5),101)
a

array([[101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101],
       [101, 101, 101, 101, 101]])

In [33]:
a =np.ones((3,3))*30
a

array([[30., 30., 30.],
       [30., 30., 30.],
       [30., 30., 30.]])

In [36]:
# to get identity matrix
a = np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
a = np.identity((4)*40)
a

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
#creating ndarray with existing  data

In [38]:
#conver list into array
a=[1,3,4]
array_a =np.asarray(a)
array_a

array([1, 3, 4])

In [39]:
#convert tuple to array
a=(1,3,4)
array_a =np.asarray(a)
array_a

array([1, 3, 4])

In [ ]:
a=