In [1]:
import numpy as np

In [2]:
prime_array = np.array([2,3,5,7,9])
print(prime_array)

[2 3 5 7 9]


In [3]:
print(prime_array.shape)

(5,)


In [4]:
prim_array = np.array([[2,3,5,7,9],[1,2,3,4,5]])
print(prim_array)

[[2 3 5 7 9]
 [1 2 3 4 5]]


In [5]:
print(prim_array.shape)

(2, 5)


In [6]:
#3d array
num_array = np.array([[[1,2,3],[2,3,4]],
                     [[3,4,5],[5,6,7]]])
print(num_array)

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [5 6 7]]]


In [7]:
print(num_array.shape)

(2, 2, 3)


In [8]:
#4r array
num_arr =([[[[1,2],[2,3],[4,5],[8,6]],
           [2,3],[4,5],[5,6],[6,7]]])
print(num_arr)

[[[[1, 2], [2, 3], [4, 5], [8, 6]], [2, 3], [4, 5], [5, 6], [6, 7]]]
