In [1]:
import numpy as np


np.flatten functiom


In [2]:
random_3d =np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3d}")
print(f"The shape of array is {random_3d.shape}")

The defined array is 
[[[24 12 35 33 17 29]
  [25 25 40 43 38 30]
  [42 42 34 44 16 39]
  [24 32 28 44 18 23]]

 [[24 19 36 29 31 37]
  [26 18 14 32 14 32]
  [42 19 34 27 26 33]
  [33 42 27 15 37 29]]]
The shape of array is (2, 4, 6)


In [3]:
#flatten The 3d array
random_3d.flatten()

array([24, 12, 35, 33, 17, 29, 25, 25, 40, 43, 38, 30, 42, 42, 34, 44, 16,
       39, 24, 32, 28, 44, 18, 23, 24, 19, 36, 29, 31, 37, 26, 18, 14, 32,
       14, 32, 42, 19, 34, 27, 26, 33, 33, 42, 27, 15, 37, 29])

pandas is python package providing flexible 

In [4]:
import pandas as pd


In [5]:
#our first series
number_series =pd.Series([1,2,4,5,6])
print(number_series)

0    1
1    2
2    4
3    5
4    6
dtype: int64


In [6]:
# same series buth with different indices
number_series =pd.Series([1,2,4,5,6],index=['a','b','c','d','e'],name='Number')
print(number_series)

a    1
b    2
c    4
d    5
e    6
Name: Number, dtype: int64


In [7]:
# indexing
print(number_series[0])
print(number_series['c'])

1
4


In [8]:
#creating our data frame usinh 2-D numpy array
some_2d_array =np.random.randint(4,10 ,(2,3))  #2-D numpy array(2=rows,3=column)
print(some_2d_array)
first_datafame = pd.DataFrame(some_2d_array,columns=["Akshay","Shiv","aman"])
print(first_datafame)

[[7 9 9]
 [8 6 5]]
   Akshay  Shiv  aman
0       7     9     9
1       8     6     5


In [9]:
#creating our data frame usinh 2-D numpy array
some_2d_array =np.random.randint(4,10 ,(4,3))  #2-D numpy array
first_datafame = pd.DataFrame(some_2d_array,columns=["Akshay","Shiv","Koko"])
print(first_datafame)

   Akshay  Shiv  Koko
0       6     8     8
1       9     4     4
2       7     4     5
3       5     8     6


In [10]:
#using a list of dictionaries
#list of dicitionaries
list_of_dict =[{'a':1,'b':2,'c':3},{'a':10,'b':20,'c':30}]
df = pd.DataFrame(list_of_dict)
df

a   b   c
0   1   2   3
1  10  20  30

In [11]:
#what happens if the  number of keys are different in two dictionaries
list_of_dict =[{'a':1,'c':3},{'a':10,'b':20,'c':30}]
df = pd.DataFrame(list_of_dict,index=['first','second'])
df

a   c     b
first    1   3   NaN
second  10  30  20.0

In [12]:
#dataframe using list of tuple
actor_name=['aman',"srk","khan"]
actor_age=[12,45,65]
list_tuple =list(zip(actor_name,actor_age))
#converting the list of tuples into pandas dataframe
actor_df =pd.DataFrame(list_tuple,columns=['Name','age'])

  
   



     
actor_df

Name  age
0  aman   12
1   srk   45
2  khan   65

In [13]:
import pandas as pd
df =pd.read_csv("Train.csv")

In [14]:
df.head(2)

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility    Item_Type  \
0           FDA15         9.30          Low Fat         0.016047        Dairy   
1           DRC01         5.92          Regular         0.019278  Soft Drinks   

   Item_MRP Outlet_Identifier  Outlet_Establishment_Year Outlet_Size  \
0  249.8092            OUT049                       1999      Medium   
1   48.2692            OUT018                       2009      Medium   

  Outlet_Location_Type        Outlet_Type  Item_Outlet_Sales  
0               Tier 1  Supermarket Type1          3735.1380  
1               Tier 3  Supermarket Type2           443.4228

In [15]:
list(df.columns)

['Item_Identifier',
 'Item_Weight',
 'Item_Fat_Content',
 'Item_Visibility',
 'Item_Type',
 'Item_MRP',
 'Outlet_Identifier',
 'Outlet_Establishment_Year',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type',
 'Item_Outlet_Sales']

In [16]:
df.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales'],
      dtype='object')

In [17]:
df.tail()


Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

               Item_Type  Item_MRP Outlet_Identifier  \
8518         Snack Foods  214.5218            OUT013   
8519        Baking Goods  108.1570            OUT045   
8520  Health and Hygiene   85.1224            OUT035   
8521         Snack Foods  103.1332            OUT018   
8522         Soft Drinks   75.4670            OUT046   

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
8518                       1987        High               Tier 3   
8519                       2002         NaN               Tier 2   
8520                       2004       Small               Tier 2   
8521                       2009      Medium               Tier 3   
8522                       1997       Small               Tier 1   

            Outlet_Type  Item_Outlet_Sales  
8518  Supermarket Type1          2778.3834  
8519  Supermarket Type1           549.2850  
8520  Supermarket Type1          1193.1136  
8521  Supermarket Type2          1845.5976  
8522  Supermarket Type1           765.6700

In [18]:
df.info

<bound method DataFrame.info of      Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
0              FDA15        9.300          Low Fat         0.016047   
1              DRC01        5.920          Regular         0.019278   
2              FDN15       17.500          Low Fat         0.016760   
3              FDX07       19.200          Regular         0.000000   
4              NCD19        8.930          Low Fat         0.000000   
...              ...          ...              ...              ...   
8518           FDF22        6.865          Low Fat         0.056783   
8519           FDS36        8.380          Regular         0.046982   
8520           NCJ29       10.600          Low Fat         0.035186   
8521           FDN46        7.210          Regular         0.145221   
8522           DRG01       14.800          Low Fat         0.044878   

                  Item_Type  Item_MRP Outlet_Identifier  \
0                     Dairy  249.8092            OUT049 

In [19]:
#rename the columns name
df.rename(columns={'Item_Identifier':'Item_details'},inplace=True)


In [20]:
df.head()

Item_details  Item_Weight Item_Fat_Content  Item_Visibility  \
0        FDA15         9.30          Low Fat         0.016047   
1        DRC01         5.92          Regular         0.019278   
2        FDN15        17.50          Low Fat         0.016760   
3        FDX07        19.20          Regular         0.000000   
4        NCD19         8.93          Low Fat         0.000000   

               Item_Type  Item_MRP Outlet_Identifier  \
0                  Dairy  249.8092            OUT049   
1            Soft Drinks   48.2692            OUT018   
2                   Meat  141.6180            OUT049   
3  Fruits and Vegetables  182.0950            OUT010   
4              Household   53.8614            OUT013   

   Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
0                       1999      Medium               Tier 1   
1                       2009      Medium               Tier 3   
2                       1999      Medium               Tier 1   
3                       1998         NaN               Tier 3   
4                       1987        High               Tier 3   

         Outlet_Type  Item_Outlet_Sales  
0  Supermarket Type1          3735.1380  
1  Supermarket Type2           443.4228  
2  Supermarket Type1          2097.2700  
3      Grocery Store           732.3800  
4  Supermarket Type1           994.7052