In [36]:
import numpy as np


np.flatten functiom


In [37]:
random_3d =np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3d}")
print(f"The shape of array is {random_3d.shape}")

The defined array is 
[[[15 15 34 13 34 38]
  [11 22 42 40 34 28]
  [15 22 14 17 10 13]
  [41 37 10 34 16 40]]

 [[32 18 11 15 30 34]
  [37 12 18 35 21 15]
  [40 14 12 31 28 26]
  [16 33 20 34 21 28]]]
The shape of array is (2, 4, 6)


In [38]:
#flatten The 3d array
random_3d.flatten()

array([15, 15, 34, 13, 34, 38, 11, 22, 42, 40, 34, 28, 15, 22, 14, 17, 10,
       13, 41, 37, 10, 34, 16, 40, 32, 18, 11, 15, 30, 34, 37, 12, 18, 35,
       21, 15, 40, 14, 12, 31, 28, 26, 16, 33, 20, 34, 21, 28])

pandas is python package providing flexible 

In [39]:
import pandas as pd


In [40]:
#our first series
number_series =pd.Series([1,2,4,5,6])
print(number_series)

0    1
1    2
2    4
3    5
4    6
dtype: int64


In [41]:
# same series buth with different indices
number_series =pd.Series([1,2,4,5,6],index=['a','b','c','d','e'],name='Number')
print(number_series)

a    1
b    2
c    4
d    5
e    6
Name: Number, dtype: int64


In [42]:
# indexing
print(number_series[0])
print(number_series['c'])

1
4


In [43]:
#creating our data frame usinh 2-D numpy array
some_2d_array =np.random.randint(4,10 ,(2,3))  #2-D numpy array(2=rows,3=column)
print(some_2d_array)
first_datafame = pd.DataFrame(some_2d_array,columns=["Akshay","Shiv","aman"])
print(first_datafame)

[[7 4 7]
 [7 4 7]]
   Akshay  Shiv  aman
0       7     4     7
1       7     4     7


In [44]:
#creating our data frame usinh 2-D numpy array
some_2d_array =np.random.randint(4,10 ,(4,3))  #2-D numpy array
first_datafame = pd.DataFrame(some_2d_array,columns=["Akshay","Shiv","Koko"])
print(first_datafame)

   Akshay  Shiv  Koko
0       7     4     4
1       5     5     8
2       5     4     4
3       4     7     6


In [58]:
first_datafame.loc['Akshay']

KeyError: 'Akshay'