In [5]:
import numpy as np


np.flatten functiom


In [6]:
random_3d =np.array(np.random.randint(10,45,(2,4,6)))
print(f"The defined array is \n{random_3d}")
print(f"The shape of array is {random_3d.shape}")

The defined array is 
[[[40 37 35 12 21 13]
  [31 38 13 38 18 22]
  [33 19 15 38 19 30]
  [19 23 40 36 34 42]]

 [[14 41 32 39 26 13]
  [23 19 38 15 35 29]
  [26 10 16 25 36 37]
  [20 20 43 13 16 41]]]
The shape of array is (2, 4, 6)


In [7]:
#flatten The 3d array
random_3d.flatten()

array([40, 37, 35, 12, 21, 13, 31, 38, 13, 38, 18, 22, 33, 19, 15, 38, 19,
       30, 19, 23, 40, 36, 34, 42, 14, 41, 32, 39, 26, 13, 23, 19, 38, 15,
       35, 29, 26, 10, 16, 25, 36, 37, 20, 20, 43, 13, 16, 41])

pandas is python package providing flexible 

In [8]:
import pandas as pd


In [9]:
#our first series
number_series =pd.Series([1,2,4,5,6])
print(number_series)

0    1
1    2
2    4
3    5
4    6
dtype: int64


In [10]:
# same series buth with different indices
number_series =pd.Series([1,2,4,5,6],index=['a','b','c','d','e'],name='Number')
print(number_series)

a    1
b    2
c    4
d    5
e    6
Name: Number, dtype: int64


In [11]:
# indexing
print(number_series[0])
print(number_series['c'])

1
4


In [12]:
#creating our data frame usinh 2-D numpy array
some_2d_array =np.random.randint(4,10 ,(2,3))  #2-D numpy array(2=rows,3=column)
print(some_2d_array)
first_datafame = pd.DataFrame(some_2d_array,columns=["Akshay","Shiv","aman"])
print(first_datafame)

[[6 9 9]
 [8 6 4]]
   Akshay  Shiv  aman
0       6     9     9
1       8     6     4


In [13]:
#creating our data frame usinh 2-D numpy array
some_2d_array =np.random.randint(4,10 ,(4,3))  #2-D numpy array
first_datafame = pd.DataFrame(some_2d_array,columns=["Akshay","Shiv","Koko"])
print(first_datafame)

   Akshay  Shiv  Koko
0       6     8     5
1       5     4     5
2       6     5     6
3       7     5     4


In [15]:
#using a list of dictionaries
#list of dicitionaries
list_of_dict =[{'a':1,'b':2,'c':3},{'a':10,'b':20,'c':30}]
df = pd.DataFrame(list_of_dict)
df

a   b   c
0   1   2   3
1  10  20  30

In [18]:
#what happens if the  number of keys are different in two dictionaries
list_of_dict =[{'a':1,'c':3},{'a':10,'b':20,'c':30}]
df = pd.DataFrame(list_of_dict,index=['first','second'])
df

a   c     b
first    1   3   NaN
second  10  30  20.0

In [21]:
#dataframe using list of tuple
actor_name=['aman',"srk","khan"]
actor_age=[12,45,65]
list_tuple =list(zip(actor_name,actor_age))
#converting the list of tuples into pandas dataframe
actor_df =pd.DataFrame(list_tuple,columns=['Name','age'])

  
   



     
actor_df

Name  age
0  aman   12
1   srk   45
2  khan   65